### ISSUE TITLE
provide async server-side rendering example

### ISSUE THREAD

**Issue by ms88privat** [loggur/bloggur#1]
Thanks for your effort building this library.

I would really love to know, how to use this concept with async data fetching. 

For example when the User requests the URL "/books/3", I have to fetch the data needed to render all the components somewhere (e.g. componentDidMount). 

How would I manage this for the server-side rendering (e.g. how to get the initialState) ? 

Greetings

**Comment by timbur** [comment]
Use redux-thunk and return a thunk within an action during initialization. You can dispatch an action immediately as the provider's store is initialized by including an enhancer with your provider. I'd link to an example but I'm on my phone. You should be able to find one around here somewhere though. :)

**Comment by timbur** [comment]
Hello again!  Did you figure it out?

If you look at https://github.com/loggur/provide-theme/blob/master/src/index.js, you can see we import [`redux-thunk`](https://github.com/gaearon/redux-thunk) and then [export it as middleware](https://github.com/loggur/provide-theme/blob/master/src/index.js#L270-L272) so that it may be used within the theme provider.  And then you can see where the `loadTheme` action returns a function which accepts `dispatch` as an argument so that we can fetch the theme asynchronously here: https://github.com/loggur/provide-theme/blob/master/src/index.js#L62-L103

**Comment by timbur** [comment]
Hello again!  The best way to achieve this is through replication.  v6.0 of `react-redux-provide` should hopefully be released some time this week which should make things like this extremely easy to implement via replication.
