### ISSUE TITLE
use sockets instead of polling for hot reloading bundled themes

### ISSUE THREAD

**Issue by slightlytyler** [loggur/bloggur#2]
Each requests fails and then is retried

**Comment by timbur** [comment]
Have you added other `express` middleware or modified the server in any way?  What changes have you made, if any?

**Comment by slightlytyler** [comment]
No changes, I experience this after cloning the repo

**Comment by timbur** [comment]
I can't seem to reproduce this.  This is what I've tried:

1. Cloned the repo to a fresh directory.
2. Ran `npm install`.
3. Ran `npm run start:dev` for development, which works without issues.
4. Ran `npm start` for production, which also works without issues.

Do you have a `dist` directory with all the bundles?

**Comment by timbur** [comment]
Are you sure it's a 314 status code?  I'm not sure that's a valid status code: https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#3xx_Redirection

Could it be a 304 (Not Modified) status code you're seeing?  In development mode, the `provide-theme` module polls the server for updates on the current theme.  It's a temporary (hacky) method I'm using to enable "hot reloading" for bundled themes until I can figure out how to make it work with `webpack-hot-middleware` (might have to submit a PR to that repo).

Your themes load and you can modify them without issue right?

**Comment by slightlytyler** [comment]
Followed the same steps as you and I can the replicate the issue
![Uploading Screen Shot 2016-02-22 at 10.41.28 PM.png…]()

**Comment by slightlytyler** [comment]
and it's status code 304, my bad!

**Comment by slightlytyler** [comment]
No issues with themes displaying or changing

**Comment by timbur** [comment]
Ah, yeah that's just the constant polling for changes to the theme for hot reloading in development.  I wonder why it's showing up in your console like that though.  It should only show in your Network tab (also annoying though).  I'll need to take a closer look at what it would take to make things work properly with `webpack-hot-middleware`.  I want an automatic solution with `provide-theme` rather than explicitly passing the theme files to `webpack.hot.accept` in the main app, which is why I originally went the polling route.

**Comment by timbur** [comment]
I'm gonna update the topic title for future reference.  :)

**Comment by timbur** [comment]
This should be fixed with https://github.com/loggur/provide-theme/commit/da2cb6ece6f7ec3638ee884a6640932c07936087 and https://github.com/loggur/lumbur/commit/5899bec0ab40131df4111878e18e11c2ae8c5f89.  I'll update this particular repo tomorrow or the next day.
